//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheWeatherApp.Languages {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("TheWeatherApp.Languages.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Air_CO {
            get {
                return ResourceManager.GetString("Air_CO", resourceCulture);
            }
        }
        
        internal static string Air_Defra {
            get {
                return ResourceManager.GetString("Air_Defra", resourceCulture);
            }
        }
        
        internal static string Air_NO2 {
            get {
                return ResourceManager.GetString("Air_NO2", resourceCulture);
            }
        }
        
        internal static string Air_Oxone {
            get {
                return ResourceManager.GetString("Air_Oxone", resourceCulture);
            }
        }
        
        internal static string Air_SO2 {
            get {
                return ResourceManager.GetString("Air_SO2", resourceCulture);
            }
        }
        
        internal static string Eror_NoWeather_Title {
            get {
                return ResourceManager.GetString("Eror_NoWeather_Title", resourceCulture);
            }
        }
        
        internal static string Error_ConnectMessage {
            get {
                return ResourceManager.GetString("Error_ConnectMessage", resourceCulture);
            }
        }
        
        internal static string Error_ConnectTitle {
            get {
                return ResourceManager.GetString("Error_ConnectTitle", resourceCulture);
            }
        }
        
        internal static string Error_LocationNull {
            get {
                return ResourceManager.GetString("Error_LocationNull", resourceCulture);
            }
        }
        
        internal static string Error_LocationTitle {
            get {
                return ResourceManager.GetString("Error_LocationTitle", resourceCulture);
            }
        }
        
        internal static string Error_NoWeather_Message {
            get {
                return ResourceManager.GetString("Error_NoWeather_Message", resourceCulture);
            }
        }
        
        internal static string Error_Tides_NoData {
            get {
                return ResourceManager.GetString("Error_Tides_NoData", resourceCulture);
            }
        }
        
        internal static string Error_Tides_Title {
            get {
                return ResourceManager.GetString("Error_Tides_Title", resourceCulture);
            }
        }
        
        internal static string Pos_Lat {
            get {
                return ResourceManager.GetString("Pos_Lat", resourceCulture);
            }
        }
        
        internal static string Pos_Lng {
            get {
                return ResourceManager.GetString("Pos_Lng", resourceCulture);
            }
        }
        
        internal static string Temp_Max {
            get {
                return ResourceManager.GetString("Temp_Max", resourceCulture);
            }
        }
        
        internal static string Temp_Min {
            get {
                return ResourceManager.GetString("Temp_Min", resourceCulture);
            }
        }
        
        internal static string Weather_Additional {
            get {
                return ResourceManager.GetString("Weather_Additional", resourceCulture);
            }
        }
        
        internal static string Weather_Alerts {
            get {
                return ResourceManager.GetString("Weather_Alerts", resourceCulture);
            }
        }
        
        internal static string Weather_TotalRain {
            get {
                return ResourceManager.GetString("Weather_TotalRain", resourceCulture);
            }
        }
        
        internal static string Weather_MaxWind {
            get {
                return ResourceManager.GetString("Weather_MaxWind", resourceCulture);
            }
        }
        
        internal static string Weather_Quality {
            get {
                return ResourceManager.GetString("Weather_Quality", resourceCulture);
            }
        }
        
        internal static string Weather_AveHumid {
            get {
                return ResourceManager.GetString("Weather_AveHumid", resourceCulture);
            }
        }
        
        internal static string Weather_TotalSnow {
            get {
                return ResourceManager.GetString("Weather_TotalSnow", resourceCulture);
            }
        }
        
        internal static string Weather_UV {
            get {
                return ResourceManager.GetString("Weather_UV", resourceCulture);
            }
        }
        
        internal static string Weather_RainChance {
            get {
                return ResourceManager.GetString("Weather_RainChance", resourceCulture);
            }
        }
        
        internal static string Weather_ChanceSnow {
            get {
                return ResourceManager.GetString("Weather_ChanceSnow", resourceCulture);
            }
        }
        
        internal static string Alert_Severity {
            get {
                return ResourceManager.GetString("Alert_Severity", resourceCulture);
            }
        }
        
        internal static string Alert_Urgency {
            get {
                return ResourceManager.GetString("Alert_Urgency", resourceCulture);
            }
        }
        
        internal static string Alert_Areas {
            get {
                return ResourceManager.GetString("Alert_Areas", resourceCulture);
            }
        }
        
        internal static string Alert_Category {
            get {
                return ResourceManager.GetString("Alert_Category", resourceCulture);
            }
        }
        
        internal static string Alert_Event {
            get {
                return ResourceManager.GetString("Alert_Event", resourceCulture);
            }
        }
        
        internal static string Alert_Certain {
            get {
                return ResourceManager.GetString("Alert_Certain", resourceCulture);
            }
        }
        
        internal static string Alert_Desc {
            get {
                return ResourceManager.GetString("Alert_Desc", resourceCulture);
            }
        }
        
        internal static string Alert_Instruct {
            get {
                return ResourceManager.GetString("Alert_Instruct", resourceCulture);
            }
        }
        
        internal static string Alert_Effective {
            get {
                return ResourceManager.GetString("Alert_Effective", resourceCulture);
            }
        }
        
        internal static string Alert_Expires {
            get {
                return ResourceManager.GetString("Alert_Expires", resourceCulture);
            }
        }
        
        internal static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings_Title", resourceCulture);
            }
        }
        
        internal static string Settings_NumDays {
            get {
                return ResourceManager.GetString("Settings_NumDays", resourceCulture);
            }
        }
        
        internal static string Settings_Alerts {
            get {
                return ResourceManager.GetString("Settings_Alerts", resourceCulture);
            }
        }
        
        internal static string Settings_Air {
            get {
                return ResourceManager.GetString("Settings_Air", resourceCulture);
            }
        }
        
        internal static string Settings_Save {
            get {
                return ResourceManager.GetString("Settings_Save", resourceCulture);
            }
        }
        
        internal static string Tide_Time {
            get {
                return ResourceManager.GetString("Tide_Time", resourceCulture);
            }
        }
        
        internal static string Tide_Height {
            get {
                return ResourceManager.GetString("Tide_Height", resourceCulture);
            }
        }
        
        internal static string Tide_Type {
            get {
                return ResourceManager.GetString("Tide_Type", resourceCulture);
            }
        }
    }
}
