using Newtonsoft.Json;
using TheWeatherApp.Models;

namespace TheWeatherApp.Tests.Helpers
{
    public class MockWeatherDataSetup
    {
        public WeatherForecast Setup_WeatherData()
        {
            var data = @"
{
    ""location"": {
        ""name"": ""Newton le Willows"",
        ""region"": ""Merseyside"",
        ""country"": ""UK"",
        ""lat"": 53.4539985656738,
        ""lon"": -2.63199996948242,
        ""tz_id"": ""Europe/London"",
        ""localtime_epoch"": 1749891744,
        ""localtime"": ""2025-06-14 10:02""
    },
    ""current"": {
        ""last_updated_epoch"": 1749891600,
        ""last_updated"": ""2025-06-14 10:00"",
        ""temp_c"": 17.3,
        ""temp_f"": 63.1,
        ""is_day"": 1,
        ""condition"": {
            ""text"": ""Partly cloudy"",
            ""icon"": ""//cdn.weatherapi.com/weather/64x64/day/116.png"",
            ""code"": 1003
        },
        ""wind_mph"": 9.2,
        ""wind_kph"": 14.8,
        ""wind_degree"": 206,
        ""wind_dir"": ""SSW"",
        ""pressure_mb"": 1010.0,
        ""pressure_in"": 29.83,
        ""precip_mm"": 1.17,
        ""precip_in"": 0.05,
        ""humidity"": 88,
        ""cloud"": 50,
        ""feelslike_c"": 17.3,
        ""feelslike_f"": 63.1,
        ""windchill_c"": 17.2,
        ""windchill_f"": 62.9,
        ""heatindex_c"": 17.2,
        ""heatindex_f"": 62.9,
        ""dewpoint_c"": 15.9,
        ""dewpoint_f"": 60.6,
        ""vis_km"": 10.0,
        ""vis_miles"": 6.0,
        ""uv"": 0.5,
        ""gust_mph"": 11.6,
        ""gust_kph"": 18.6,
        ""air_quality"": {
            ""co"": 360.75,
            ""no2"": 27.01,
            ""o3"": 57.0,
            ""so2"": 6.29,
            ""pm2_5"": 13.875,
            ""pm10"": 15.91,
            ""us-epa-index"": 1,
            ""gb-defra-index"": 2
        }
    },
    ""forecast"": {
        ""forecastday"": [
            {
                ""date"": ""2025-06-14"",
                ""date_epoch"": 1749859200,
                ""day"": {
                    ""maxtemp_c"": 19.7,
                    ""maxtemp_f"": 67.4,
                    ""mintemp_c"": 12.4,
                    ""mintemp_f"": 54.4,
                    ""avgtemp_c"": 15.5,
                    ""avgtemp_f"": 59.9,
                    ""maxwind_mph"": 13.4,
                    ""maxwind_kph"": 21.6,
                    ""totalprecip_mm"": 13.04,
                    ""totalprecip_in"": 0.51,
                    ""totalsnow_cm"": 0.0,
                    ""avgvis_km"": 8.8,
                    ""avgvis_miles"": 5.0,
                    ""avghumidity"": 88,
                    ""daily_will_it_rain"": 1,
                    ""daily_chance_of_rain"": 96,
                    ""daily_will_it_snow"": 0,
                    ""daily_chance_of_snow"": 0,
                    ""condition"": {
                        ""text"": ""Moderate rain"",
                        ""icon"": ""//cdn.weatherapi.com/weather/64x64/day/302.png"",
                        ""code"": 1189
                    },
                    ""uv"": 1.1,
                    ""air_quality"": {
                        ""co"": 357.7159999999999,
                        ""no2"": 19.9356,
                        ""o3"": 58.12,
                        ""so2"": 1.3541999999999998,
                        ""pm2_5"": 9.102000000000002,
                        ""pm10"": 11.499600000000003,
                        ""us-epa-index"": 1,
                        ""gb-defra-index"": 1
                    }
                },
                ""astro"": {
                    ""sunrise"": ""04:42 AM"",
                    ""sunset"": ""09:41 PM"",
                    ""moonrise"": ""12:08 AM"",
                    ""moonset"": ""07:06 AM"",
                    ""moon_phase"": ""Waning Gibbous"",
                    ""moon_illumination"": 93,
                    ""is_moon_up"": 0,
                    ""is_sun_up"": 0
                },
                ""hour"": [
                    {
                        ""time_epoch"": 1749855600,
                        ""time"": ""2025-06-14 00:00"",
                        ""temp_c"": 13.9,
                        ""temp_f"": 57.0,
                        ""is_day"": 0,
                        ""condition"": {
                            ""text"": ""Moderate or heavy rain shower"",
                            ""icon"": ""//cdn.weatherapi.com/weather/64x64/night/356.png"",
                            ""code"": 1243
                        },
                        ""wind_mph"": 2.5,
                        ""wind_kph"": 4.0,
                        ""wind_degree"": 7,
                        ""wind_dir"": ""N"",
                        ""pressure_mb"": 1015.0,
                        ""pressure_in"": 29.97,
                        ""precip_mm"": 3.85,
                        ""precip_in"": 0.15,
                        ""snow_cm"": 0.0,
                        ""humidity"": 97,
                        ""cloud"": 100,
                        ""feelslike_c"": 14.4,
                        ""feelslike_f"": 58.0,
                        ""windchill_c"": 14.4,
                        ""windchill_f"": 58.0,
                        ""heatindex_c"": 13.9,
                        ""heatindex_f"": 57.0,
                        ""dewpoint_c"": 13.3,
                        ""dewpoint_f"": 56.0,
                        ""will_it_rain"": 1,
                        ""chance_of_rain"": 100,
                        ""will_it_snow"": 0,
                        ""chance_of_snow"": 0,
                        ""vis_km"": 7.0,
                        ""vis_miles"": 4.0,
                        ""gust_mph"": 4.0,
                        ""gust_kph"": 6.4,
                        ""uv"": 0,
                        ""air_quality"": {
                            ""co"": 357.05,
                            ""no2"": 31.45,
                            ""o3"": 43.0,
                            ""so2"": 1.295,
                            ""pm2_5"": 14.06,
                            ""pm10"": 19.24,
                            ""us-epa-index"": 1,
                            ""gb-defra-index"": 2
                        }
                    },
                    {
                        ""time_epoch"": 1749859200,
                        ""time"": ""2025-06-14 01:00"",
                        ""temp_c"": 14.0,
                        ""temp_f"": 57.2,
                        ""is_day"": 0,
                        ""condition"": {
                            ""text"": ""Light rain shower"",
                            ""icon"": ""//cdn.weatherapi.com/weather/64x64/night/353.png"",
                            ""code"": 1240
                        },
                        ""wind_mph"": 3.6,
                        ""wind_kph"": 5.8,
                        ""wind_degree"": 10,
                        ""wind_dir"": ""N"",
                        ""pressure_mb"": 1014.0,
                        ""pressure_in"": 29.93,
                        ""precip_mm"": 0.22,
                        ""precip_in"": 0.01,
                        ""snow_cm"": 0.0,
                        ""humidity"": 97,
                        ""cloud"": 100,
                        ""feelslike_c"": 14.2,
                        ""feelslike_f"": 57.5,
                        ""windchill_c"": 14.2,
                        ""windchill_f"": 57.5,
                        ""heatindex_c"": 14.0,
                        ""heatindex_f"": 57.2,
                        ""dewpoint_c"": 13.5,
                        ""dewpoint_f"": 56.3,
                        ""will_it_rain"": 1,
                        ""chance_of_rain"": 100,
                        ""will_it_snow"": 0,
                        ""chance_of_snow"": 0,
                        ""vis_km"": 10.0,
                        ""vis_miles"": 6.0,
                        ""gust_mph"": 6.3,
                        ""gust_kph"": 10.1,
                        ""uv"": 0,
                        ""air_quality"": {
                            ""co"": 368.15,
                            ""no2"": 31.265,
                            ""o3"": 39.0,
                            ""so2"": 1.11,
                            ""pm2_5"": 14.43,
                            ""pm10"": 17.02,
                            ""us-epa-index"": 1,
                            ""gb-defra-index"": 2
                        }
                    },
                    {
                        ""time_epoch"": 1749862800,
                        ""time"": ""2025-06-14 02:00"",
                        ""temp_c"": 14.0,
                        ""temp_f"": 57.2,
                        ""is_day"": 0,
                        ""condition"": {
                            ""text"": ""Light rain shower"",
                            ""icon"": ""//cdn.weatherapi.com/weather/64x64/night/353.png"",
                            ""code"": 1240
                        },
                        ""wind_mph"": 1.3,
                        ""wind_kph"": 2.2,
                        ""wind_degree"": 310,
                        ""wind_dir"": ""NW"",
                        ""pressure_mb"": 1013.0,
                        ""pressure_in"": 29.91,
                        ""precip_mm"": 0.57,
                        ""precip_in"": 0.02,
                        ""snow_cm"": 0.0,
                        ""humidity"": 98,
                        ""cloud"": 100,
                        ""feelslike_c"": 14.0,
                        ""feelslike_f"": 57.2,
                        ""windchill_c"": 14.0,
                        ""windchill_f"": 57.2,
                        ""heatindex_c"": 14.0,
                        ""heatindex_f"": 57.2,
                        ""dewpoint_c"": 13.6,
                        ""dewpoint_f"": 56.6,
                        ""will_it_rain"": 1,
                        ""chance_of_rain"": 100,
                        ""will_it_snow"": 0,
                        ""chance_of_snow"": 0,
                        ""vis_km"": 10.0,
                        ""vis_miles"": 6.0,
                        ""gust_mph"": 2.3,
                        ""gust_kph"": 3.8,
                        ""uv"": 0,
                        ""air_quality"": {
                            ""co"": 347.8,
                            ""no2"": 27.38,
                            ""o3"": 43.0,
                            ""so2"": 0.925,
                            ""pm2_5"": 12.025,
                            ""pm10"": 13.875,
                            ""us-epa-index"": 1,
                            ""gb-defra-index"": 2
                        }
                    },
                    {
                        ""time_epoch"": 1749866400,
                        ""time"": ""2025-06-14 03:00"",
                        ""temp_c"": 14.3,
                        ""temp_f"": 57.7,
                        ""is_day"": 0,
                        ""condition"": {
                            ""text"": ""Light rain shower"",
                            ""icon"": ""//cdn.weatherapi.com/weather/64x64/night/353.png"",
                            ""code"": 1240
                        },
                        ""wind_mph"": 2.0,
                        ""wind_kph"": 3.2,
                        ""wind_degree"": 181,
                        ""wind_dir"": ""S"",
                        ""pressure_mb"": 1012.0,
                        ""pressure_in"": 29.89,
                        ""precip_mm"": 0.68,
                        ""precip_in"": 0.03,
                        ""snow_cm"": 0.0,
                        ""humidity"": 99,
                        ""cloud"": 100,
                        ""feelslike_c"": 15.1,
                        ""feelslike_f"": 59.2,
                        ""windchill_c"": 15.1,
                        ""windchill_f"": 59.2,
                        ""heatindex_c"": 14.3,
                        ""heatindex_f"": 57.7,
                        ""dewpoint_c"": 14.1,
                        ""dewpoint_f"": 57.4,
                        ""will_it_rain"": 1,
                        ""chance_of_rain"": 100,
                        ""will_it_snow"": 0,
                        ""chance_of_snow"": 0,
                        ""vis_km"": 10.0,
                        ""vis_miles"": 6.0,
                        ""gust_mph"": 3.2,
                        ""gust_kph"": 5.2,
                        ""uv"": 0,
                        ""air_quality"": {
                            ""co"": 344.1,
                            ""no2"": 27.75,
                            ""o3"": 43.0,
                            ""so2"": 0.74,
                            ""pm2_5"": 10.36,
                            ""pm10"": 12.765,
                            ""us-epa-index"": 1,
                            ""gb-defra-index"": 1
                        }
                    },
                    {
                        ""time_epoch"": 1749870000,
                        ""time"": ""2025-06-14 04:00"",
                        ""temp_c"": 14.5,
                        ""temp_f"": 58.1,
                        ""is_day"": 0,
                        ""condition"": {
                            ""text"": ""Fog"",
                            ""icon"": ""//cdn.weatherapi.com/weather/64x64/night/248.png"",
                            ""code"": 1135
                        },
                        ""wind_mph"": 2.2,
                        ""wind_kph"": 3.6,
                        ""wind_degree"": 149,
                        ""wind_dir"": ""SSE"",
                        ""pressure_mb"": 1012.0,
                        ""pressure_in"": 29.87,
                        ""precip_mm"": 0.13,
                        ""precip_in"": 0.01,
                        ""snow_cm"": 0.0,
                        ""humidity"": 99,
                        ""cloud"": 100,
                        ""feelslike_c"": 15.2,
                        ""feelslike_f"": 59.4,
                        ""windchill_c"": 15.2,
                        ""windchill_f"": 59.4,
                        ""heatindex_c"": 14.5,
                        ""heatindex_f"": 58.1,
                        ""dewpoint_c"": 14.4,
                        ""dewpoint_f"": 57.9,
                        ""will_it_rain"": 1,
                        ""chance_of_rain"": 100,
                        ""will_it_snow"": 0,
                        ""chance_of_snow"": 0,
                        ""vis_km"": 0.0,
                        ""vis_miles"": 0.0,
                        ""gust_mph"": 3.7,
                        ""gust_kph"": 5.9,
                        ""uv"": 0,
                        ""air_quality"": {
                            ""co"": 347.8,
                            ""no2"": 34.41,
                            ""o3"": 32.0,
                            ""so2"": 0.74,
                            ""pm2_5"": 9.25,
                            ""pm10"": 10.915,
                            ""us-epa-index"": 1,
                            ""gb-defra-index"": 1
                        }
                    },
                    {
                        ""time_epoch"": 1749873600,
                        ""time"": ""2025-06-14 05:00"",
                        ""temp_c"": 14.8,
                        ""temp_f"": 58.6,
                        ""is_day"": 1,
                        ""condition"": {
                            ""text"": ""Light rain shower"",
                            ""icon"": ""//cdn.weatherapi.com/weather/64x64/day/353.png"",
                            ""code"": 1240
                        },
                        ""wind_mph"": 3.6,
                        ""wind_kph"": 5.8,
                        ""wind_degree"": 165,
                        ""wind_dir"": ""SSE"",
                        ""pressure_mb"": 1011.0,
                        ""pressure_in"": 29.86,
                        ""precip_mm"": 1.27,
                        ""precip_in"": 0.05,
                        ""snow_cm"": 0.0,
                        ""humidity"": 99,
                        ""cloud"": 100,
                        ""feelslike_c"": 15.0,
                        ""feelslike_f"": 59.0,
                        ""windchill_c"": 15.0,
                        ""windchill_f"": 59.0,
                        ""heatindex_c"": 14.8,
                        ""heatindex_f"": 58.6,
                        ""dewpoint_c"": 14.7,
                        ""dewpoint_f"": 58.4,
                        ""will_it_rain"": 1,
                        ""chance_of_rain"": 100,
                        ""will_it_snow"": 0,
                        ""chance_of_snow"": 0,
                        ""vis_km"": 10.0,
                        ""vis_miles"": 6.0,
                        ""gust_mph"": 5.8,
                        ""gust_kph"": 9.3,
                        ""uv"": 0.0,
                        ""air_quality"": {
                            ""co"": 333.0,
                            ""no2"": 34.04,
                            ""o3"": 32.0,
                            ""so2"": 0.925,
                            ""pm2_5"": 9.25,
                            ""pm10"": 10.175,
                            ""us-epa-index"": 1,
                            ""gb-defra-index"": 1
                        }
                    },
                    {
                        ""time_epoch"": 1749877200,
                        ""time"": ""2025-06-14 06:00"",
                        ""temp_c"": 14.7,
                        ""temp_f"": 58.4,
                        ""is_day"": 1,
                        ""condition"": {
                            ""text"": ""Light rain shower"",
                            ""icon"": ""//cdn.weatherapi.com/weather/64x64/day/353.png"",
                            ""code"": 1240
                        },
                        ""wind_mph"": 3.1,
                        ""wind_kph"": 5.0,
                        ""wind_degree"": 195,
                        ""wind_dir"": ""SSW"",
                        ""pressure_mb"": 1011.0,
                        ""pressure_in"": 29.85,
                        ""precip_mm"": 1.38,
                        ""precip_in"": 0.05,
                        ""snow_cm"": 0.0,
                        ""humidity"": 99,
                        ""cloud"": 100,
                        ""feelslike_c"": 15.0,
                        ""feelslike_f"": 59.1,
                        ""windchill_c"": 15.0,
                        ""windchill_f"": 59.1,
                        ""heatindex_c"": 14.7,
                        ""heatindex_f"": 58.4,
                        ""dewpoint_c"": 14.6,
                        ""dewpoint_f"": 58.2,
                        ""will_it_rain"": 1,
                        ""chance_of_rain"": 100,
                        ""will_it_snow"": 0,
                        ""chance_of_snow"": 0,
                        ""vis_km"": 10.0,
                        ""vis_miles"": 6.0,
                        ""gust_mph"": 5.5,
                        ""gust_kph"": 8.8,
                        ""uv"": 0.0,
                        ""air_quality"": {
                            ""co"": 333.0,
                            ""no2"": 35.335,
                            ""o3"": 42.0,
                            ""so2"": 0.925,
                            ""pm2_5"": 9.62,
                            ""pm10"": 11.285,
                            ""us-epa-index"": 1,
                            ""gb-defra-index"": 1
                        }
                    },
                    {
                        ""time_epoch"": 1749880800,
                        ""time"": ""2025-06-14 07:00"",
                        ""temp_c"": 14.4,
                        ""temp_f"": 58.0,
                        ""is_day"": 1,
                        ""condition"": {
                            ""text"": ""Light rain shower"",
                            ""icon"": ""//cdn.weatherapi.com/weather/64x64/day/353.png"",
                            ""code"": 1240
                        },
                        ""wind_mph"": 3.1,
                        ""wind_kph"": 5.0,
                        ""wind_degree"": 206,
                        ""wind_dir"": ""SSW"",
                        ""pressure_mb"": 1011.0,
                        ""pressure_in"": 29.85,
                        ""precip_mm"": 0.86,
                        ""precip_in"": 0.03,
                        ""snow_cm"": 0.0,
                        ""humidity"": 99,
                        ""cloud"": 100,
                        ""feelslike_c"": 14.8,
                        ""feelslike_f"": 58.6,
                        ""windchill_c"": 14.8,
                        ""windchill_f"": 58.6,
                        ""heatindex_c"": 14.4,
                        ""heatindex_f"": 58.0,
                        ""dewpoint_c"": 14.3,
                        ""dewpoint_f"": 57.8,
                        ""will_it_rain"": 1,
                        ""chance_of_rain"": 100,
                        ""will_it_snow"": 0,
                        ""chance_of_snow"": 0,
                        ""vis_km"": 10.0,
                        ""vis_miles"": 6.0,
                        ""gust_mph"": 4.8,
                        ""gust_kph"": 7.7,
                        ""uv"": 0.0,
                        ""air_quality"": {
                            ""co"": 345.95,
                            ""no2"": 34.78,
                            ""o3"": 42.0,
                            ""so2"": 1.295,
                            ""pm2_5"": 9.62,
                            ""pm10"": 11.47,
                            ""us-epa-index"": 1,
                            ""gb-defra-index"": 1
                        }
                    },
                    {
                        ""time_epoch"": 1749884400,
                        ""time"": ""2025-06-14 08:00"",
                        ""temp_c"": 14.5,
                        ""temp_f"": 58.2,
                        ""is_day"": 1,
                        ""condition"": {
                            ""text"": ""Light rain shower"",
                            ""icon"": ""//cdn.weatherapi.com/weather/64x64/day/353.png"",
                            ""code"": 1240
                        },
                        ""wind_mph"": 4.5,
                        ""wind_kph"": 7.2,
                        ""wind_degree"": 189,
                        ""wind_dir"": ""S"",
                        ""pressure_mb"": 1011.0,
                        ""pressure_in"": 29.85,
                        ""precip_mm"": 0.72,
                        ""precip_in"": 0.03,
                        ""snow_cm"": 0.0,
                        ""humidity"": 99,
                        ""cloud"": 100,
                        ""feelslike_c"": 14.5,
                        ""feelslike_f"": 58.0,
                        ""windchill_c"": 14.5,
                        ""windchill_f"": 58.0,
                        ""heatindex_c"": 14.5,
                        ""heatindex_f"": 58.2,
                        ""dewpoint_c"": 14.4,
                        ""dewpoint_f"": 57.9,
                        ""will_it_rain"": 1,
                        ""chance_of_rain"": 100,
                        ""will_it_snow"": 0,
                        ""chance_of_snow"": 0,
                        ""vis_km"": 10.0,
                        ""vis_miles"": 6.0,
                        ""gust_mph"": 6.6,
                        ""gust_kph"": 10.6,
                        ""uv"": 0.1,
                        ""air_quality"": {
                            ""co"": 379.25,
                            ""no2"": 39.22,
                            ""o3"": 37.0,
                            ""so2"": 1.665,
                            ""pm2_5"": 9.805,
                            ""pm10"": 11.84,
                            ""us-epa-index"": 1,
                            ""gb-defra-index"": 1
                        }
                    },
                    {
                        ""time_epoch"": 1749888000,
                        ""time"": ""2025-06-14 09:00"",
                        ""temp_c"": 15.2,
                        ""temp_f"": 59.4,
                        ""is_day"": 1,
                        ""condition"": {
                            ""text"": ""Fog"",
                            ""icon"": ""//cdn.weatherapi.com/weather/64x64/day/248.png"",
                            ""code"": 1135
                        },
                        ""wind_mph"": 4.5,
                        ""wind_kph"": 7.2,
                        ""wind_degree"": 167,
                        ""wind_dir"": ""SSE"",
                        ""pressure_mb"": 1011.0,
                        ""pressure_in"": 29.85,
                        ""precip_mm"": 0.03,
                        ""precip_in"": 0.0,
                        ""snow_cm"": 0.0,
                        ""humidity"": 97,
                        ""cloud"": 100,
                        ""feelslike_c"": 15.2,
                        ""feelslike_f"": 59.4,
                        ""windchill_c"": 15.2,
                        ""windchill_f"": 59.4,
                        ""heatindex_c"": 15.2,
                        ""heatindex_f"": 59.4,
                        ""dewpoint_c"": 14.8,
                        ""dewpoint_f"": 58.7,
                        ""will_it_rain"": 1,
                        ""chance_of_rain"": 71,
                        ""will_it_snow"": 0,
                        ""chance_of_snow"": 0,
                        ""vis_km"": 0.0,
                        ""vis_miles"": 0.0,
                        ""gust_mph"": 6.4,
                        ""gust_kph"": 10.3,
                        ""uv"": 0.2,
                        ""air_quality"": {
                            ""co"": 382.95,
                            ""no2"": 34.965,
                            ""o3"": 55.0,
                            ""so2"": 2.22,
                            ""pm2_5"": 11.1,
                            ""pm10"": 13.875,
                            ""us-epa-index"": 1,
                            ""gb-defra-index"": 1
                        }
                    },
                    {
                        ""time_epoch"": 1749891600,
                        ""time"": ""2025-06-14 10:00"",
                        ""temp_c"": 17.3,
                        ""temp_f"": 63.1,
                        ""is_day"": 1,
                        ""condition"": {
                            ""text"": ""Partly cloudy"",
                            ""icon"": ""//cdn.weatherapi.com/weather/64x64/day/116.png"",
                            ""code"": 1003
                        },
                        ""wind_mph"": 9.2,
                        ""wind_kph"": 14.8,
                        ""wind_degree"": 206,
                        ""wind_dir"": ""SSW"",
                        ""pressure_mb"": 1010.0,
                        ""pressure_in"": 29.83,
                        ""precip_mm"": 1.17,
                        ""precip_in"": 0.05,
                        ""snow_cm"": 0.0,
                        ""humidity"": 88,
                        ""cloud"": 50,
                        ""feelslike_c"": 17.2,
                        ""feelslike_f"": 62.9,
                        ""windchill_c"": 17.2,
                        ""windchill_f"": 62.9,
                        ""heatindex_c"": 17.2,
                        ""heatindex_f"": 62.9,
                        ""dewpoint_c"": 15.9,
                        ""dewpoint_f"": 60.6,
                        ""will_it_rain"": 1,
                        ""chance_of_rain"": 100,
                        ""will_it_snow"": 0,
                        ""chance_of_snow"": 0,
                        ""vis_km"": 10.0,
                        ""vis_miles"": 6.0,
                        ""gust_mph"": 11.6,
                        ""gust_kph"": 18.6,
                        ""uv"": 0.5,
                        ""air_quality"": {
                            ""co"": 360.75,
                            ""no2"": 27.01,
                            ""o3"": 57.0,
                            ""so2"": 6.29,
                            ""pm2_5"": 13.875,
                            ""pm10"": 15.91,
                            ""us-epa-index"": 1,
                            ""gb-defra-index"": 2
                        }
                    },
                    {
                        ""time_epoch"": 1749895200,
                        ""time"": ""2025-06-14 11:00"",
                        ""temp_c"": 17.3,
                        ""temp_f"": 63.2,
                        ""is_day"": 1,
                        ""condition"": {
                            ""text"": ""Light rain shower"",
                            ""icon"": ""//cdn.weatherapi.com/weather/64x64/day/353.png"",
                            ""code"": 1240
                        },
                        ""wind_mph"": 9.4,
                        ""wind_kph"": 15.1,
                        ""wind_degree"": 237,
                        ""wind_dir"": ""WSW"",
                        ""pressure_mb"": 1011.0,
                        ""pressure_in"": 29.86,
                        ""precip_mm"": 0.71,
                        ""precip_in"": 0.03,
                        ""snow_cm"": 0.0,
                        ""humidity"": 89,
                        ""cloud"": 73,
                        ""feelslike_c"": 17.3,
                        ""feelslike_f"": 63.2,
                        ""windchill_c"": 17.3,
                        ""windchill_f"": 63.2,
                        ""heatindex_c"": 17.3,
                        ""heatindex_f"": 63.2,
                        ""dewpoint_c"": 15.4,
                        ""dewpoint_f"": 59.8,
                        ""will_it_rain"": 1,
                        ""chance_of_rain"": 100,
                        ""will_it_snow"": 0,
                        ""chance_of_snow"": 0,
                        ""vis_km"": 10.0,
                        ""vis_miles"": 6.0,
                        ""gust_mph"": 15.8,
                        ""gust_kph"": 25.5,
                        ""uv"": 2.1,
                        ""air_quality"": {
                            ""co"": 349.65,
                            ""no2"": 15.17,
                            ""o3"": 66.0,
                            ""so2"": 2.775,
                            ""pm2_5"": 13.875,
                            ""pm10"": 16.28,
                            ""us-epa-index"": 1,
                            ""gb-defra-index"": 2
                        }
                    },
                    {
                        ""time_epoch"": 1749898800,
                        ""time"": ""2025-06-14 12:00"",
                        ""temp_c"": 18.1,
                        ""temp_f"": 64.7,
                        ""is_day"": 1,
                        ""condition"": {
                            ""text"": ""Light rain shower"",
                            ""icon"": ""//cdn.weatherapi.com/weather/64x64/day/353.png"",
                            ""code"": 1240
                        },
                        ""wind_mph"": 10.5,
                        ""wind_kph"": 16.9,
                        ""wind_degree"": 242,
                        ""wind_dir"": ""WSW"",
                        ""pressure_mb"": 1011.0,
                        ""pressure_in"": 29.87,
                        ""precip_mm"": 0.37,
                        ""precip_in"": 0.01,
                        ""snow_cm"": 0.0,
                        ""humidity"": 82,
                        ""cloud"": 56,
                        ""feelslike_c"": 18.2,
                        ""feelslike_f"": 64.7,
                        ""windchill_c"": 18.2,
                        ""windchill_f"": 64.7,
                        ""heatindex_c"": 18.2,
                        ""heatindex_f"": 64.7,
                        ""dewpoint_c"": 15.0,
                        ""dewpoint_f"": 59.0,
                        ""will_it_rain"": 1,
                        ""chance_of_rain"": 100,
                        ""will_it_snow"": 0,
                        ""chance_of_snow"": 0,
                        ""vis_km"": 10.0,
                        ""vis_miles"": 6.0,
                        ""gust_mph"": 14.6,
                        ""gust_kph"": 23.5,
                        ""uv"": 3.5,
                        ""air_quality"": {
                            ""co"": 342.25,
                            ""no2"": 13.875,
                            ""o3"": 75.0,
                            ""so2"": 1.48,
                            ""pm2_5"": 10.545,
                            ""pm10"": 11.84,
                            ""us-epa-index"": 1,
                            ""gb-defra-index"": 1
                        }
                    },
                    {
                        ""time_epoch"": 1749902400,
                        ""time"": ""2025-06-14 13:00"",
                        ""temp_c"": 19.7,
                        ""temp_f"": 67.4,
                        ""is_day"": 1,
                        ""condition"": {
                            ""text"": ""Patchy rain nearby"",
                            ""icon"": ""//cdn.weatherapi.com/weather/64x64/day/176.png"",
                            ""code"": 1063
                        },
                        ""wind_mph"": 10.7,
                        ""wind_kph"": 17.3,
                        ""wind_degree"": 239,
                        ""wind_dir"": ""WSW"",
                        ""pressure_mb"": 1011.0,
                        ""pressure_in"": 29.87,
                        ""precip_mm"": 0.13,
                        ""precip_in"": 0.01,
                        ""snow_cm"": 0.0,
                        ""humidity"": 67,
                        ""cloud"": 70,
                        ""feelslike_c"": 19.7,
                        ""feelslike_f"": 67.4,
                        ""windchill_c"": 19.7,
                        ""windchill_f"": 67.4,
                        ""heatindex_c"": 19.7,
                        ""heatindex_f"": 67.4,
                        ""dewpoint_c"": 13.4,
                        ""dewpoint_f"": 56.2,
                        ""will_it_rain"": 1,
                        ""chance_of_rain"": 100,
                        ""will_it_snow"": 0,
                        ""chance_of_snow"": 0,
                        ""vis_km"": 10.0,
                        ""vis_miles"": 6.0,
                        ""gust_mph"": 13.2,
                        ""gust_kph"": 21.2,
                        ""uv"": 4.3,
                        ""air_quality"": {
                            ""co"": 349.65,
                            ""no2"": 13.32,
                            ""o3"": 77.0,
                            ""so2"": 1.11,
                            ""pm2_5"": 6.845,
                            ""pm10"": 9.435,
                            ""us-epa-index"": 1,
                            ""gb-defra-index"": 1
                        }
                    },
                    {
                        ""time_epoch"": 1749906000,
                        ""time"": ""2025-06-14 14:00"",
                        ""temp_c"": 19.0,
                        ""temp_f"": 66.2,
                        ""is_day"": 1,
                        ""condition"": {
                            ""text"": ""Patchy light drizzle"",
                            ""icon"": ""//cdn.weatherapi.com/weather/64x64/day/263.png"",
                            ""code"": 1150
                        },
                        ""wind_mph"": 11.9,
                        ""wind_kph"": 19.1,
                        ""wind_degree"": 257,
                        ""wind_dir"": ""WSW"",
                        ""pressure_mb"": 1012.0,
                        ""pressure_in"": 29.88,
                        ""precip_mm"": 0.46,
                        ""precip_in"": 0.02,
                        ""snow_cm"": 0.0,
                        ""humidity"": 71,
                        ""cloud"": 74,
                        ""feelslike_c"": 19.0,
                        ""feelslike_f"": 66.2,
                        ""windchill_c"": 19.0,
                        ""windchill_f"": 66.2,
                        ""heatindex_c"": 19.0,
                        ""heatindex_f"": 66.2,
                        ""dewpoint_c"": 13.7,
                        ""dewpoint_f"": 56.7,
                        ""will_it_rain"": 1,
                        ""chance_of_rain"": 100,
                        ""will_it_snow"": 0,
                        ""chance_of_snow"": 0,
                        ""vis_km"": 5.0,
                        ""vis_miles"": 3.0,
                        ""gust_mph"": 14.1,
                        ""gust_kph"": 22.7,
                        ""uv"": 3.8,
                        ""air_quality"": {
                            ""co"": 357.05,
                            ""no2"": 8.51,
                            ""o3"": 79.0,
                            ""so2"": 0.925,
                            ""pm2_5"": 7.215,
                            ""pm10"": 8.88,
                            ""us-epa-index"": 1,
                            ""gb-defra-index"": 1
                        }
                    },
                    {
                        ""time_epoch"": 1749909600,
                        ""time"": ""2025-06-14 15:00"",
                        ""temp_c"": 17.7,
                        ""temp_f"": 63.8,
                        ""is_day"": 1,
                        ""condition"": {
                            ""text"": ""Light rain shower"",
                            ""icon"": ""//cdn.weatherapi.com/weather/64x64/day/353.png"",
                            ""code"": 1240
                        },
                        ""wind_mph"": 13.4,
                        ""wind_kph"": 21.6,
                        ""wind_degree"": 271,
                        ""wind_dir"": ""W"",
                        ""pressure_mb"": 1013.0,
                        ""pressure_in"": 29.91,
                        ""precip_mm"": 0.17,
                        ""precip_in"": 0.01,
                        ""snow_cm"": 0.0,
                        ""humidity"": 72,
                        ""cloud"": 84,
                        ""feelslike_c"": 17.7,
                        ""feelslike_f"": 63.8,
                        ""windchill_c"": 17.7,
                        ""windchill_f"": 63.8,
                        ""heatindex_c"": 17.7,
                        ""heatindex_f"": 63.8,
                        ""dewpoint_c"": 12.5,
                        ""dewpoint_f"": 54.6,
                        ""will_it_rain"": 1,
                        ""chance_of_rain"": 100,
                        ""will_it_snow"": 0,
                        ""chance_of_snow"": 0,
                        ""vis_km"": 10.0,
                        ""vis_miles"": 6.0,
                        ""gust_mph"": 17.9,
                        ""gust_kph"": 28.8,
                        ""uv"": 4.1,
                        ""air_quality"": {
                            ""co"": 349.65,
                            ""no2"": 6.845,
                            ""o3"": 77.0,
                            ""so2"": 0.925,
                            ""pm2_5"": 7.215,
                            ""pm10"": 8.695,
                            ""us-epa-index"": 1,
                            ""gb-defra-index"": 1
                        }
                    },
                    {
                        ""time_epoch"": 1749913200,
                        ""time"": ""2025-06-14 16:00"",
                        ""temp_c"": 17.1,
                        ""temp_f"": 62.8,
                        ""is_day"": 1,
                        ""condition"": {
                            ""text"": ""Patchy rain nearby"",
                            ""icon"": ""//cdn.weatherapi.com/weather/64x64/day/176.png"",
                            ""code"": 1063
                        },
                        ""wind_mph"": 11.6,
                        ""wind_kph"": 18.7,
                        ""wind_degree"": 285,
                        ""wind_dir"": ""WNW"",
                        ""pressure_mb"": 1014.0,
                        ""pressure_in"": 29.93,
                        ""precip_mm"": 0.12,
                        ""precip_in"": 0.0,
                        ""snow_cm"": 0.0,
                        ""humidity"": 71,
                        ""cloud"": 83,
                        ""feelslike_c"": 17.1,
                        ""feelslike_f"": 62.8,
                        ""windchill_c"": 17.1,
                        ""windchill_f"": 62.8,
                        ""heatindex_c"": 17.1,
                        ""heatindex_f"": 62.8,
                        ""dewpoint_c"": 11.8,
                        ""dewpoint_f"": 53.3,
                        ""will_it_rain"": 1,
                        ""chance_of_rain"": 100,
                        ""will_it_snow"": 0,
                        ""chance_of_snow"": 0,
                        ""vis_km"": 10.0,
                        ""vis_miles"": 6.0,
                        ""gust_mph"": 13.6,
                        ""gust_kph"": 21.8,
                        ""uv"": 3.9,
                        ""air_quality"": {
                            ""co"": 358.9,
                            ""no2"": 6.845,
                            ""o3"": 79.0,
                            ""so2"": 0.74,
                            ""pm2_5"": 8.325,
                            ""pm10"": 9.435,
                            ""us-epa-index"": 1,
                            ""gb-defra-index"": 1
                        }
                    },
                    {
                        ""time_epoch"": 1749916800,
                        ""time"": ""2025-06-14 17:00"",
                        ""temp_c"": 17.1,
                        ""temp_f"": 62.8,
                        ""is_day"": 1,
                        ""condition"": {
                            ""text"": ""Patchy rain nearby"",
                            ""icon"": ""//cdn.weatherapi.com/weather/64x64/day/176.png"",
                            ""code"": 1063
                        },
                        ""wind_mph"": 8.9,
                        ""wind_kph"": 14.4,
                        ""wind_degree"": 291,
                        ""wind_dir"": ""WNW"",
                        ""pressure_mb"": 1014.0,
                        ""pressure_in"": 29.94,
                        ""precip_mm"": 0.1,
                        ""precip_in"": 0.0,
                        ""snow_cm"": 0.0,
                        ""humidity"": 70,
                        ""cloud"": 79,
                        ""feelslike_c"": 17.1,
                        ""feelslike_f"": 62.8,
                        ""windchill_c"": 17.1,
                        ""windchill_f"": 62.8,
                        ""heatindex_c"": 17.1,
                        ""heatindex_f"": 62.8,
                        ""dewpoint_c"": 11.7,
                        ""dewpoint_f"": 53.0,
                        ""will_it_rain"": 1,
                        ""chance_of_rain"": 100,
                        ""will_it_snow"": 0,
                        ""chance_of_snow"": 0,
                        ""vis_km"": 10.0,
                        ""vis_miles"": 6.0,
                        ""gust_mph"": 12.3,
                        ""gust_kph"": 19.7,
                        ""uv"": 2.6,
                        ""air_quality"": {
                            ""co"": 368.15,
                            ""no2"": 7.77,
                            ""o3"": 81.0,
                            ""so2"": 0.74,
                            ""pm2_5"": 7.955,
                            ""pm10"": 9.805,
                            ""us-epa-index"": 1,
                            ""gb-defra-index"": 1
                        }
                    },
                    {
                        ""time_epoch"": 1749920400,
                        ""time"": ""2025-06-14 18:00"",
                        ""temp_c"": 16.5,
                        ""temp_f"": 61.7,
                        ""is_day"": 1,
                        ""condition"": {
                            ""text"": ""Patchy rain nearby"",
                            ""icon"": ""//cdn.weatherapi.com/weather/64x64/day/176.png"",
                            ""code"": 1063
                        },
                        ""wind_mph"": 7.6,
                        ""wind_kph"": 12.2,
                        ""wind_degree"": 295,
                        ""wind_dir"": ""WNW"",
                        ""pressure_mb"": 1014.0,
                        ""pressure_in"": 29.95,
                        ""precip_mm"": 0.07,
                        ""precip_in"": 0.0,
                        ""snow_cm"": 0.0,
                        ""humidity"": 73,
                        ""cloud"": 82,
                        ""feelslike_c"": 16.5,
                        ""feelslike_f"": 61.7,
                        ""windchill_c"": 16.5,
                        ""windchill_f"": 61.7,
                        ""heatindex_c"": 16.5,
                        ""heatindex_f"": 61.7,
                        ""dewpoint_c"": 11.6,
                        ""dewpoint_f"": 52.9,
                        ""will_it_rain"": 1,
                        ""chance_of_rain"": 100,
                        ""will_it_snow"": 0,
                        ""chance_of_snow"": 0,
                        ""vis_km"": 10.0,
                        ""vis_miles"": 6.0,
                        ""gust_mph"": 9.7,
                        ""gust_kph"": 15.6,
                        ""uv"": 1.5,
                        ""air_quality"": {
                            ""co"": 381.1,
                            ""no2"": 8.325,
                            ""o3"": 78.0,
                            ""so2"": 0.925,
                            ""pm2_5"": 5.735,
                            ""pm10"": 9.805,
                            ""us-epa-index"": 1,
                            ""gb-defra-index"": 1
                        }
                    },
                    {
                        ""time_epoch"": 1749924000,
                        ""time"": ""2025-06-14 19:00"",
                        ""temp_c"": 15.7,
                        ""temp_f"": 60.2,
                        ""is_day"": 1,
                        ""condition"": {
                            ""text"": ""Patchy rain nearby"",
                            ""icon"": ""//cdn.weatherapi.com/weather/64x64/day/176.png"",
                            ""code"": 1063
                        },
                        ""wind_mph"": 5.4,
                        ""wind_kph"": 8.6,
                        ""wind_degree"": 292,
                        ""wind_dir"": ""WNW"",
                        ""pressure_mb"": 1015.0,
                        ""pressure_in"": 29.97,
                        ""precip_mm"": 0.03,
                        ""precip_in"": 0.0,
                        ""snow_cm"": 0.0,
                        ""humidity"": 79,
                        ""cloud"": 66,
                        ""feelslike_c"": 15.7,
                        ""feelslike_f"": 60.2,
                        ""windchill_c"": 15.7,
                        ""windchill_f"": 60.2,
                        ""heatindex_c"": 15.7,
                        ""heatindex_f"": 60.2,
                        ""dewpoint_c"": 12.0,
                        ""dewpoint_f"": 53.5,
                        ""will_it_rain"": 0,
                        ""chance_of_rain"": 64,
                        ""will_it_snow"": 0,
                        ""chance_of_snow"": 0,
                        ""vis_km"": 10.0,
                        ""vis_miles"": 6.0,
                        ""gust_mph"": 7.3,
                        ""gust_kph"": 11.7,
                        ""uv"": 0.7,
                        ""air_quality"": {
                            ""co"": 373.7,
                            ""no2"": 8.325,
                            ""o3"": 75.0,
                            ""so2"": 0.925,
                            ""pm2_5"": 6.845,
                            ""pm10"": 9.065,
                            ""us-epa-index"": 1,
                            ""gb-defra-index"": 1
                        }
                    },
                    {
                        ""time_epoch"": 1749927600,
                        ""time"": ""2025-06-14 20:00"",
                        ""temp_c"": 14.4,
                        ""temp_f"": 57.9,
                        ""is_day"": 1,
                        ""condition"": {
                            ""text"": ""Cloudy "",
                            ""icon"": ""//cdn.weatherapi.com/weather/64x64/day/119.png"",
                            ""code"": 1006
                        },
                        ""wind_mph"": 3.1,
                        ""wind_kph"": 5.0,
                        ""wind_degree"": 285,
                        ""wind_dir"": ""WNW"",
                        ""pressure_mb"": 1016.0,
                        ""pressure_in"": 29.99,
                        ""precip_mm"": 0.0,
                        ""precip_in"": 0.0,
                        ""snow_cm"": 0.0,
                        ""humidity"": 86,
                        ""cloud"": 78,
                        ""feelslike_c"": 14.7,
                        ""feelslike_f"": 58.5,
                        ""windchill_c"": 14.7,
                        ""windchill_f"": 58.5,
                        ""heatindex_c"": 14.4,
                        ""heatindex_f"": 57.9,
                        ""dewpoint_c"": 12.1,
                        ""dewpoint_f"": 53.7,
                        ""will_it_rain"": 0,
                        ""chance_of_rain"": 0,
                        ""will_it_snow"": 0,
                        ""chance_of_snow"": 0,
                        ""vis_km"": 10.0,
                        ""vis_miles"": 6.0,
                        ""gust_mph"": 4.9,
                        ""gust_kph"": 7.9,
                        ""uv"": 0.3,
                        ""air_quality"": {
                            ""co"": 347.8,
                            ""no2"": 8.14,
                            ""o3"": 69.0,
                            ""so2"": 0.925,
                            ""pm2_5"": 7.4,
                            ""pm10"": 10.175,
                            ""us-epa-index"": 1,
                            ""gb-defra-index"": 1
                        }
                    },
                    {
                        ""time_epoch"": 1749931200,
                        ""time"": ""2025-06-14 21:00"",
                        ""temp_c"": 13.2,
                        ""temp_f"": 55.8,
                        ""is_day"": 1,
                        ""condition"": {
                            ""text"": ""Partly Cloudy "",
                            ""icon"": ""//cdn.weatherapi.com/weather/64x64/day/116.png"",
                            ""code"": 1003
                        },
                        ""wind_mph"": 2.5,
                        ""wind_kph"": 4.0,
                        ""wind_degree"": 283,
                        ""wind_dir"": ""WNW"",
                        ""pressure_mb"": 1016.0,
                        ""pressure_in"": 30.0,
                        ""precip_mm"": 0.0,
                        ""precip_in"": 0.0,
                        ""snow_cm"": 0.0,
                        ""humidity"": 90,
                        ""cloud"": 53,
                        ""feelslike_c"": 13.7,
                        ""feelslike_f"": 56.7,
                        ""windchill_c"": 13.7,
                        ""windchill_f"": 56.7,
                        ""heatindex_c"": 13.2,
                        ""heatindex_f"": 55.8,
                        ""dewpoint_c"": 11.6,
                        ""dewpoint_f"": 52.9,
                        ""will_it_rain"": 0,
                        ""chance_of_rain"": 0,
                        ""will_it_snow"": 0,
                        ""chance_of_snow"": 0,
                        ""vis_km"": 10.0,
                        ""vis_miles"": 6.0,
                        ""gust_mph"": 4.3,
                        ""gust_kph"": 7.0,
                        ""uv"": 0.0,
                        ""air_quality"": {
                            ""co"": 345.95,
                            ""no2"": 11.1,
                            ""o3"": 63.0,
                            ""so2"": 1.11,
                            ""pm2_5"": 6.845,
                            ""pm10"": 10.36,
                            ""us-epa-index"": 1,
                            ""gb-defra-index"": 1
                        }
                    },
                    {
                        ""time_epoch"": 1749934800,
                        ""time"": ""2025-06-14 22:00"",
                        ""temp_c"": 12.6,
                        ""temp_f"": 54.7,
                        ""is_day"": 0,
                        ""condition"": {
                            ""text"": ""Patchy rain nearby"",
                            ""icon"": ""//cdn.weatherapi.com/weather/64x64/night/176.png"",
                            ""code"": 1063
                        },
                        ""wind_mph"": 2.0,
                        ""wind_kph"": 3.2,
                        ""wind_degree"": 223,
                        ""wind_dir"": ""SW"",
                        ""pressure_mb"": 1016.0,
                        ""pressure_in"": 30.01,
                        ""precip_mm"": 0.01,
                        ""precip_in"": 0.0,
                        ""snow_cm"": 0.0,
                        ""humidity"": 93,
                        ""cloud"": 89,
                        ""feelslike_c"": 13.3,
                        ""feelslike_f"": 55.9,
                        ""windchill_c"": 13.3,
                        ""windchill_f"": 55.9,
                        ""heatindex_c"": 12.6,
                        ""heatindex_f"": 54.7,
                        ""dewpoint_c"": 11.6,
                        ""dewpoint_f"": 52.8,
                        ""will_it_rain"": 1,
                        ""chance_of_rain"": 79,
                        ""will_it_snow"": 0,
                        ""chance_of_snow"": 0,
                        ""vis_km"": 10.0,
                        ""vis_miles"": 6.0,
                        ""gust_mph"": 3.7,
                        ""gust_kph"": 5.9,
                        ""uv"": 0,
                        ""air_quality"": {
                            ""co"": 358.9,
                            ""no2"": 14.06,
                            ""o3"": 58.0,
                            ""so2"": 1.295,
                            ""pm2_5"": 6.475,
                            ""pm10"": 10.915,
                            ""us-epa-index"": 1,
                            ""gb-defra-index"": 1
                        }
                    },
                    {
                        ""time_epoch"": 1749938400,
                        ""time"": ""2025-06-14 23:00"",
                        ""temp_c"": 12.4,
                        ""temp_f"": 54.4,
                        ""is_day"": 0,
                        ""condition"": {
                            ""text"": ""Patchy rain nearby"",
                            ""icon"": ""//cdn.weatherapi.com/weather/64x64/night/176.png"",
                            ""code"": 1063
                        },
                        ""wind_mph"": 3.1,
                        ""wind_kph"": 5.0,
                        ""wind_degree"": 184,
                        ""wind_dir"": ""S"",
                        ""pressure_mb"": 1017.0,
                        ""pressure_in"": 30.02,
                        ""precip_mm"": 0.01,
                        ""precip_in"": 0.0,
                        ""snow_cm"": 0.0,
                        ""humidity"": 94,
                        ""cloud"": 95,
                        ""feelslike_c"": 12.5,
                        ""feelslike_f"": 54.5,
                        ""windchill_c"": 12.5,
                        ""windchill_f"": 54.5,
                        ""heatindex_c"": 12.4,
                        ""heatindex_f"": 54.4,
                        ""dewpoint_c"": 11.4,
                        ""dewpoint_f"": 52.6,
                        ""will_it_rain"": 1,
                        ""chance_of_rain"": 79,
                        ""will_it_snow"": 0,
                        ""chance_of_snow"": 0,
                        ""vis_km"": 10.0,
                        ""vis_miles"": 6.0,
                        ""gust_mph"": 5.6,
                        ""gust_kph"": 9.1,
                        ""uv"": 0,
                        ""air_quality"": {
                            ""co"": 364.45,
                            ""no2"": 17.76,
                            ""o3"": 51.0,
                            ""so2"": 1.295,
                            ""pm2_5"": 7.4,
                            ""pm10"": 11.47,
                            ""us-epa-index"": 1,
                            ""gb-defra-index"": 1
                        }
                    }
                ]
            }
        ]
    },
    ""alerts"": {
        ""alert"": [
            {
                ""headline"": ""Yellow Thunderstorm Warning issued for United Kingdom - Central, Tayside & Fife | Grampian | Highlands & Eilean Siar | North East England | North West England | Strathclyde | SW Scotland, Lothian Borders | Yorkshire & Humber"",
                ""msgtype"": ""Update"",
                ""severity"": ""Moderate"",
                ""urgency"": ""Immediate"",
                ""areas"": ""Central, Tayside & Fife | Grampian | Highlands & Eilean Siar | North East England | North West England | Strathclyde | SW Scotland, Lothian Borders | Yorkshire & Humber"",
                ""category"": ""Met"",
                ""certainty"": ""Possible"",
                ""event"": ""Yellow thunderstorm warning"",
                ""note"": """",
                ""effective"": """",
                ""expires"": ""2025-06-14T17:00:00+00:00"",
                ""desc"": ""Information on update: The warning area has been shrunk across England and Wales. Further areas of heavy rain and some thunderstorms will move north during Saturday. \n\nRainfall will vary across the warning area and some places will avoid the heaviest rain. However, 15-30 mm of rain is likely in places with some areas perhaps seeing 30-50 mm falling in a few hours. Event rainfall could reach 60-80 mm in some locations. Strong gusts and hail may also accompany some of the thunderstorms.\n\nFor further details see https://www.metoffice.gov.uk/weather/warnings-and-advice/uk-warnings"",
                ""instruction"": ""Consider if your location is at risk of flash flooding. If so, consider preparing a flood plan and an emergency flood kit.\n\nPrepare to protect your property and people from injury. Before gusty winds arrive, check to ensure moveable objects or temporary structures are well secured. Items include; bins, garden furniture, trampolines, tents, gazebos, sheds, and fences.\n\nGive yourself the best chance of avoiding delays by checking road conditions if driving, or bus and train timetables, amending your travel plans if necessary.\n\nPeople cope better with power cuts when they have prepared for them in advance. It’s easy to do; consider gathering torches and batteries, a mobile phone power pack and other essential items.\n\nIf you find yourself outside and hear thunder, protect yourself by finding a safe enclosed shelter (such as a car). Do not shelter under or near trees, or other structures which may be struck by lightning. If you are on an elevated area move to lower ground.\n\nBe prepared for weather warnings to change quickly: when a weather warning is issued, the Met Office recommends staying up to date with the weather forecast in your area.""
            },
            {
                ""headline"": ""Yellow Thunderstorm Warning issued for United Kingdom - Central, Tayside & Fife | Grampian | Highlands & Eilean Siar | North East England | North West England | Strathclyde | SW Scotland, Lothian Borders | Yorkshire & Humber"",
                ""msgtype"": ""Update"",
                ""severity"": ""Moderate"",
                ""urgency"": ""Immediate"",
                ""areas"": ""Central, Tayside & Fife | Grampian | Highlands & Eilean Siar | North East England | North West England | Strathclyde | SW Scotland, Lothian Borders | Yorkshire & Humber"",
                ""category"": ""Met"",
                ""certainty"": ""Possible"",
                ""event"": ""Yellow thunderstorm warning"",
                ""note"": """",
                ""effective"": """",
                ""expires"": ""2025-06-14T17:00:00+00:00"",
                ""desc"": ""Information on update: The warning area has been shrunk across England and Wales. Further areas of heavy rain and some thunderstorms will move north during Saturday. \n\nRainfall will vary across the warning area and some places will avoid the heaviest rain. However, 15-30 mm of rain is likely in places with some areas perhaps seeing 30-50 mm falling in a few hours. Event rainfall could reach 60-80 mm in some locations. Strong gusts and hail may also accompany some of the thunderstorms.\n\nFor further details see https://www.metoffice.gov.uk/weather/warnings-and-advice/uk-warnings"",
                ""instruction"": ""Consider if your location is at risk of flash flooding. If so, consider preparing a flood plan and an emergency flood kit.\n\nPrepare to protect your property and people from injury. Before gusty winds arrive, check to ensure moveable objects or temporary structures are well secured. Items include; bins, garden furniture, trampolines, tents, gazebos, sheds, and fences.\n\nGive yourself the best chance of avoiding delays by checking road conditions if driving, or bus and train timetables, amending your travel plans if necessary.\n\nPeople cope better with power cuts when they have prepared for them in advance. It’s easy to do; consider gathering torches and batteries, a mobile phone power pack and other essential items.\n\nIf you find yourself outside and hear thunder, protect yourself by finding a safe enclosed shelter (such as a car). Do not shelter under or near trees, or other structures which may be struck by lightning. If you are on an elevated area move to lower ground.\n\nBe prepared for weather warnings to change quickly: when a weather warning is issued, the Met Office recommends staying up to date with the weather forecast in your area.""
            }
        ]
    }
}";
            return JsonConvert.DeserializeObject<WeatherForecast>(data);
        }
    }
}
